### ISSUE TITLE
Unable to distinguish reliably application staged with Eirini or Docker images

### ISSUE THREAD

**Issue by mudler** [cloudfoundry-incubator/eirini#112]
### Description

While pushing an application with cf and Eirini, there is no way to tell if the runtime app was pushed from a docker image or staged with Eirini

### Steps to reproduce

 Push an standard cf app, and an app with ```cf push test-docker --docker-image viovanov/node-env-tiny```

### What was expected to happen

Have a clear way to distinguish an app pushed from docker images and one that was being staged. 
 
### What actually happened

The only difference between the two applications is only the image

### Suggested fix (optional)

For example, an annotation or a label in the pod which makes it easy to figure out what the source was. The only thing I can think of now is checking the image source being used.

### Additional information (optional)

It's hard for EiriniX extension to figure out where are the applications coming from, making solutions to address this overkill

**Comment by jimmykarily** [comment]
Ths reason we need this is to be able to add a grace period to apps so we can collect the logs before the pod is gone. A solution like the one requested here (for tasks though), should deprecate this issue: https://github.com/cloudfoundry-incubator/eirini/issues/115
