### ISSUE TITLE
Set timeouts for requests to Kubernetes API

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry-incubator/eirini#123]
### Description

Currently it appears Eirini does not set a timeout when making calls to the Kubernetes API. In situations of network issues or load, requests may be left open for hours or more. 

### Steps to reproduce

Have Eirini send a request to a Kubernetes API endpoint that does not respond.

### What was expected to happen

The request should eventually timeout

### What actually happened

The request stays open forever.

### Additional information (optional)

https://github.com/kubernetes/kubernetes/pull/17074

**Comment by gcapizzi** [comment]
This is done! We have added a 60 seconds timeout for our calls to the Kubernetes API, and wired up everything so that cancelling the HTTP request to Eirini also cancels any calls to Kubernetes. Thanks for reporting this!
