### ISSUE TITLE
Eirini does not work with K8s 1.13 

### ISSUE THREAD

**Issue by smoser-ibm** [cloudfoundry-incubator/eirini#54]
### Description

Eirini does not work with K8s 1.13 

### Steps to reproduce

1. Go to your favorite cloud provider
2. Provision a K8s cluster with version 1.13 or higher 
3. Deploy an eirini on it 

### What was expected to happen
It should work 

### What actually happened

It doesn't

**Comment by alex-slynko** [comment]
Master branch of Eirini can be deployed on IKS 1.13 (or other installation with metrics service).
