### ISSUE TITLE
cf cli error when multiple requests to modify app happen together

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry-incubator/eirini#58]
### Description

If multiple requests try to modify the same app concurrently, you can get this error back from the cf cli:
```
Runner error: Operation cannot be fulfilled on statefulsets.apps "uptimer-app-8a203fc5-f28d-4237-a334-e609-5439e8b96f": the object has been modified; please apply your changes to the latest version and try again
```

We saw this when trying to delete an app, and we were able to reproduce it by scaling an app multiple times in a short window.

### Steps to reproduce

cf scale -i 2 APPNAME &
cf scale -i 1 APPNAME &
cf scale -i 2 APPNAME &
cf scale -i 1 APPNAME &

### What was expected to happen

No errors occur, the last request to be made is the state of the application.

### What actually happened

If the last request fails, the CC data is updated with the desired number of apps, but it takes a couple of minutes for the app to actually converge on that number.

**Comment by gdankov** [comment]
Thanks for reporting this @jpalermo!

It should be fixed with commit 5baa1ae782975c17a92a29bdf18334c68e1e9536
