### ISSUE TITLE
eirini app pod names only give a hint on cf spaces

### ISSUE THREAD

**Issue by svollath** [cloudfoundry-incubator/eirini#62]
### Description

  When I push an app, the resulting pod name seems to consist of `<cfappname>-<cfspace>-<id>-<instanceNo>`, so e.g. "dora-test-9912c1e844-0".
If you have multiple Organaziations, with a space named e.g. "test" in each of them, it will be confusing to just have "Space" as part of the pod name.

### Steps to reproduce

  * Create two Organizations, e.g. "qa" and "qa1" and create a space "test" in each of them
  * push an app to each of the targets - e.g. dora1 to qa/test, and dora to qa1/test :)
  * find resulting pod names to be, e.g.

```
> kubectl get pods -n eirini
NAME                      READY     STATUS    RESTARTS   AGE
dora-test-9912c1e844-0    1/1       Running   0          1d
dora1-test-1f0dcb591f-0   1/1       Running   0          31m
```

### What was expected to happen

  * The pod name to include "cf-org" and "cf-space"

### What actually happened

  Only "cf-space", which can consist of identical values, was chosen without "cf-org", which has to be unique - it's confusing, because "cfappname" has to be unique already.

### Suggested fix (optional)

  In order to be helpful (like human readable) the pod name should include "cf-org" as well, so consist of `<cfappname>-<cforg>-<cfspace>-<id>-<instanceNo>`.

**Comment by julz** [comment]
Hi @svollath sorry for slow response - the pod names are really just intended to be a little bit of sugar to make it easy to scan the list, the names have a maximum length and adding org name would likely exceed it. We plan to add the space and org guids as labels to the pods to make it easy to search and display with kubectl.
