### ISSUE TITLE
Memory Consumption goes high for eirini  

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry-incubator/eirini#64]
### Description

  We did a scalability tests on Eirini. We used [diego stress test](https://github.com/cloudfoundry/diego-stress-tests) framework to push applications. We set max-in flight as 50(concurrent pushes). We reached till 14000 applications and after that we faced statefulset [issue](https://github.com/kubernetes/kubernetes/issues/78682) .Might be because of Kube Controller Manager throttling.

![image](https://user-images.githubusercontent.com/29627753/59092096-65be9300-892e-11e9-9447-9dcfa4965dc7.png)

During the load test , we could see Eirini memory usage keeps piling till 6GB as in the above image. 

### Steps to reproduce

 Deploy 14000 applications 

### Additional information (optional)

  Is profiling enabled in Eirini, so that we can dig down ?

**Comment by alex-slynko** [comment]
@KesavanKing 	we have fixed several issues in Eirini since that time. 
When we deployed 1000 applications, the memory stayed at 400 MB after one day.

**Comment by julz** [comment]
Hi @KesavanKing - I'm going to close this story for now since we suspect it was fixed by various improvements. Please feel free to re-open or create a new issue if not!
