### ISSUE TITLE
App container metrics have incorrect/hardcoded values

### ISSUE THREAD

**Issue by madamkiwi** [cloudfoundry-incubator/eirini#68]
### Description

We have observed that Eirini is incorrectly reporting disk and memory quotas for apps. It looks like it is always using a hardcoded/default value of 10 bytes, which is certainly not the case.

### Steps to reproduce

1. Push an app
1. `cf tail that-app`
    - `cf tail` is available via the `log-cache` plugin: https://github.com/cloudfoundry/log-cache-cli

### What was expected to happen

> 2019-07-26T15:46:43.48-0700 [that-app/0] GAUGE cpu:1.000000 percentage disk:42000000.000000 bytes disk_quota:<REAL_DISK_QUOTA> bytes memory:24690688.000000 bytes memory_quota:<REAL_MEMORY_QUOTA> bytes

### What actually happened

> 2019-07-26T15:46:43.48-0700 [that-app/0] GAUGE cpu:1.000000 percentage disk:42000000.000000 bytes disk_quota:10.000000 bytes memory:24690688.000000 bytes memory_quota:10.000000 bytes

Thanks,
K + @jspawar

**Comment by mnitchev** [comment]
Hello @madamkiwi && @jspawar,

We looked into it and it looks like we did hardcode the values [here](https://github.com/cloudfoundry-incubator/eirini/blob/fa13d3fe0bd2b55aa52a877ad7353ecce2129c14/k8s/metrics.go#L80-L82). We fixed the memory quota in [this commit](https://github.com/cloudfoundry-incubator/eirini/commit/018c45027120e74e1ec9268bc74cb89fcaa492ab), but adding disk quotas and monitoring is not as trivial ([support for it was introduced in v1.15](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage), but the feature is still in beta). 

We'll leave this issue open and we'll add tracker stories for this feature and get back to you.


Best Regards,
@mnitchev && @akshaymankar

**Comment by akshaymankar** [comment]
Hello again,

We've created stories for:
1. Actually limiting disk in application instances [#167645230](https://www.pivotaltracker.com/story/show/167645230)
1. Reporting disk usage correctly [#167648185](https://www.pivotaltracker.com/story/show/167648185)

Please follow those for closer updates.

**Comment by jspawar** [comment]
Great, thanks y'all!

**Comment by alex-slynko** [comment]
This has been fixed in Eirini 0.19
