### ISSUE TITLE
Eirini reports CPU in incorrect units

### ISSUE THREAD

**Issue by jrussett** [cloudfoundry-incubator/eirini#75]
### Description

Eirini is not converting from `kubectl top` cpu units to `cf app` cpu units correctly.

* `kubectl top` displays cpu used in milliunits (1000m = 1 core). 
* `cf app` displays cpu in percentage (100% = 1 core).
* Eirini is reporting number of cores, rounded to the nearest integer (1.0 = 1 core).

This causes `cf app` to display, for example, `2.0%` instead of `195%`.

### Steps to reproduce

```
$ cf push dora

$ kubectl -n eirini exec dora-s-491a8c664e-0 -- /home/vcap/app/stress --cpu 2

$ kubectl -n eirini top pod
NAME                  CPU(cores)   MEMORY(bytes)
dora-s-491a8c664e-0   1948m        25Mi

$ cf app dora
...
     state     since                  cpu    memory        disk          details
#0   running   2019-06-15T08:01:24Z   2.0%   25.1M of 1G   40.1M of 1G

$ cf tail dora -n1
Retrieving logs for app dora in org o / space s as admin...

   2019-06-17T09:04:25.79-0700 [dora/0] GAUGE cpu:2.000000 percentage disk:42000000.000000 bytes disk_quota:10.000000 bytes memory:26431488.000000 bytes memory_quota:10.000000 bytes
```

### What was expected to happen

```
$ cf app dora
...
     state     since                  cpu    memory        disk          details
#0   running   2019-06-15T08:01:24Z   194.8%   25.1M of 1G   40.1M of 1G
```

### What actually happened

```
$ cf app dora
...
     state     since                  cpu    memory        disk          details
#0   running   2019-06-15T08:01:24Z   2.0%   25.1M of 1G   40.1M of 1G
```

**Comment by mnitchev** [comment]
Hello @jrussett,

Thanks for pointing this out. 
Fixed by [49ffd098](https://github.com/cloudfoundry-incubator/eirini/commit/49ffd09863f1ec2fc9d2b0d73aa0ca8f764f3194).

Regards,
@mnitchev
