### ISSUE TITLE
ServiceAccount per App?

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry-incubator/eirini#78]
As we scope out more of the routing and networking stuff, one thing that has come up is how to do app identity.

CF Diego has [instance identity certs](https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html), which are different for each app instance.

These support [route integrity](https://docs.cloudfoundry.org/concepts/http-routing.html#with-tls) and may also be used by applications to mTLS auth to system components like CredHub, and also for mTLS to other apps.

In the Eirini/K8s world, it isn't clear that we need identity per instance or pod.  But it sure would be nice to have identity per application, in the form of a dedicate service account for each CF App (or potentially per process type?).

That identity could be used for authN for mTLS between apps and also for route integrity from the routing tier to applications, e.g. using Istio or something else that can mTLS to sidecars (e.g. #72).

What do y'all think?

cc @tcdowney @ndhanushkodi

**Comment by julz** [comment]
This sounds pretty legit to us, we're wondering if this is something another team - for example y'all :) - may want to own and ship via something like [`Eirinix`](https://github.com/SUSE/eirinix), though? (although open to arguments that we should standardise it in the "core" eirini).

**Comment by tcdowney** [comment]
We've started this discussion up on cf-for-k8s: https://github.com/cloudfoundry/cf-for-k8s/issues/368

Current proposal is for us to own a mutating webhook and controller that does this. Feedback welcome on that issue!
