### ISSUE TITLE
mTLS using standard TSL library

### ISSUE THREAD

**Issue by dtimm** [cloudfoundry-incubator/eirini#80]
### Description

Eirini currently uses its own golang implementation of mTLS. There is a CF tls config package that stays up-to-date with internal guidelines for TLS configuration.

### Suggested fix (optional)

Use [code.cloudfoundry.org/tlsconfig](https://github.com/cloudfoundry/tlsconfig) to generate TLS config.

**Comment by georgethebeatle** [comment]
Thanks for reporting this @dtimm. This commit fixes that: 1c0351b626dde9a7f07e32ae5a066a03f9fff94b
