### ISSUE TITLE
Org/space/app name annotations

### ISSUE THREAD

**Issue by pianohacker** [cloudfoundry-incubator/eirini#83]
### Description

The Log Egress (Loggregator) team would like to send logs from apps to many downstream consumers, most of which have historically depended on app metadata to help filter and annotate those logs. Some of those are native to the platform, like Log Cache, but others are offsite, such as Splunk, Papertrail, or AppDynamics. To make this happen, annotations on the StatefulSet/Pods with the name of the application, org and space would be extremely useful.

While it is possible for this information to become out of date using the `cf rename-*` commands, the current implementation in CF continues to send the original name, so it would be fine for Eirini not to update them.

## Suggested Fix

Given that the `cloudfoundry.org/application_name` and `space_name` annotations already seem to exist (https://github.com/cloudfoundry-incubator/eirini/blob/ca5617920508538c055485a30362b4240b2d35ee/k8s/statefulset.go#L28), we suggest adding a `cloudfoundry.org/org_name` or `organization_name` annotation.

**Comment by alex-slynko** [comment]
This should work in the latest version. Feel free to reopen the issue if still see problems
