### ISSUE TITLE
Pod and Service labels consistency 

### ISSUE THREAD

**Issue by mike1808** [cloudfoundry-incubator/eirini#85]
It'll be nice to have the same labels for pods and services to able to reuse the selector find services and pods corresponding to an app GUID. Right now pods have `cloudfoundry.org/app_guid` and `cloudfoundry.org/guid` labels and services have `cloudfoundry.org/app`. 

AFAIK, having the same label is a good practice in Kubernetes which eases operators' experience and leverages tools working Kubernetes cluster to group objects under the same entity. https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

cc @ndhanushkodi

**Comment by rosenhouse** [comment]
@mike1808  What service do you speak of?  I didn't realize Eirini was creating services.

**Comment by mike1808** [comment]
@rosenhouse 🤦‍♂ cfroutesync creates services. Closing the issue.

**Comment by mike1808** [comment]
Created issue in cfroutesync repo https://github.com/cloudfoundry/cf-k8s-networking/issues/22
