### ISSUE TITLE
Making automountServiceAccountToken property configurable

### ISSUE THREAD

**Issue by ndhanushkodi** [cloudfoundry-incubator/eirini#99]
### Description

While upgrading Istio to 1.6, we discovered that the istio sidecars depend on service account tokens being mounted in environments where third party jwt tokens aren't supported (like kind). Currently this value is [hard coded to false](https://github.com/cloudfoundry-incubator/eirini/blob/7a497e5a93d3fae5efb7144020ea128641fd2807/k8s/statefulset.go#L465). We were hoping this could be configurable, so that in environments like kind, cf-for-k8s has the option to set that to true. 

### Suggested fix (optional)

There were some ideas discussed in this [thread](https://cloudfoundry.slack.com/archives/C8RU3BZ26/p1592341328308700)

Another suggestion made was to separate the service account used by the apps, from the service account used by the "statefulset desirer" [here](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1592342383102000?thread_ts=1592243893.077900&cid=CH9LF6V1P). If there are two service accounts, both would need the `automountServiceAccountToken` property to be configurable.

cc my pair @jenspinney

**Comment by mnitchev** [comment]
It looks like this is already done and accepted for App Pods (and we forgot to close this issue), but it isn't applied to Task Pods. We created a follow up issue [here](https://github.com/cloudfoundry-incubator/eirini/issues/106). Closing this issue in favour of the new one.
